//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Integration.Common.Crm3CXPhoneService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Crm3CXPhoneService.ICrm3CXPhoneCallLogService")]
    public interface ICrm3CXPhoneCallLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrm3CXPhoneCallLogService/InsertCallLog", ReplyAction="http://tempuri.org/ICrm3CXPhoneCallLogService/InsertCallLogResponse")]
        void InsertCallLog(string callId, string caller, string destination, string callType, string callState, int callLength, System.DateTime callDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrm3CXPhoneCallLogService/UpdateCallLog", ReplyAction="http://tempuri.org/ICrm3CXPhoneCallLogService/UpdateCallLogResponse")]
        void UpdateCallLog(string callId, string callState, System.DateTime callEndTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrm3CXPhoneCallLogServiceChannel : Crm.Integration.Common.Crm3CXPhoneService.ICrm3CXPhoneCallLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Crm3CXPhoneCallLogServiceClient : System.ServiceModel.ClientBase<Crm.Integration.Common.Crm3CXPhoneService.ICrm3CXPhoneCallLogService>, Crm.Integration.Common.Crm3CXPhoneService.ICrm3CXPhoneCallLogService {
        
        public Crm3CXPhoneCallLogServiceClient() {
        }
        
        public Crm3CXPhoneCallLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Crm3CXPhoneCallLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Crm3CXPhoneCallLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Crm3CXPhoneCallLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertCallLog(string callId, string caller, string destination, string callType, string callState, int callLength, System.DateTime callDate) {
            base.Channel.InsertCallLog(callId, caller, destination, callType, callState, callLength, callDate);
        }
        
        public void UpdateCallLog(string callId, string callState, System.DateTime callEndTime) {
            base.Channel.UpdateCallLog(callId, callState, callEndTime);
        }
    }
}
